/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author limon
 */
public class FrmConsultas extends javax.swing.JFrame {

    /**
     * Creates new form FrmConsultas
     */
    public FrmConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        btnConsultaCliente = new javax.swing.JLabel();
        btnConsultaArea = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MingLiU-ExtB", 1, 64)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Consultas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnRegresar.png"))); // NOI18N
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, -1));

        btnConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnConsultaCliente.png"))); // NOI18N
        btnConsultaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultaClienteMouseClicked(evt);
            }
        });
        getContentPane().add(btnConsultaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        btnConsultaArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnArea.png"))); // NOI18N
        btnConsultaArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultaAreaMouseClicked(evt);
            }
        });
        getContentPane().add(btnConsultaArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrmMesas.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        FrmInicio frm = new FrmInicio();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnConsultaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaClienteMouseClicked
        // TODO add your handling code here:
        FrmConsultaCliente frm = new FrmConsultaCliente();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultaClienteMouseClicked

    private void btnConsultaAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaAreaMouseClicked
        // TODO add your handling code here:
        FrmConsultaArea frm = new FrmConsultaArea();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultaAreaMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnConsultaArea;
    private javax.swing.JLabel btnConsultaCliente;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
