/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import com.github.lgooddatepicker.components.DateTimePicker;
import entidades.ReservaEntidad;
import java.awt.FlowLayout;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;

/**
 *
 * @author limon
 */
public class FrmConsultaCliente extends javax.swing.JFrame {

    DateTimePicker dateTimePicker = new DateTimePicker();
    
    /**
     * Creates new form FrmConsultaCliente
     */
    public FrmConsultaCliente() {
        initComponents();
        
         fldFechaReserva.setLayout(new FlowLayout());
        fldFechaReserva.add(dateTimePicker);
    }
    
    private void mostrarReservas(List<ReservaEntidad> reservas) {
        // Mostrar las reservas encontradas (esto puede hacerse usando un JTable o cualquier otro componente de UI)
        for (ReservaEntidad reserva : reservas) {
            // Aquí puedes mostrar los detalles de las reservas, por ejemplo, agregándolos a un JTable
            System.out.println("ID: " + reserva.getId() + ", Cliente: " + reserva.getNombreCompleto() + ", Fecha: " + reserva.getFechaHoraReserva());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoTextoTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoTextoNombreCompleto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JLabel();
        fldFechaReserva = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnRegresar.png"))); // NOI18N
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("MingLiU-ExtB", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Consulta cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));
        getContentPane().add(campoTextoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 230, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha de reserva");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));
        getContentPane().add(campoTextoNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 230, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre completo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnMostrar.png"))); // NOI18N
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));
        getContentPane().add(fldFechaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 350, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrmMesas.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        FrmConsultas frm = new FrmConsultas();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseClicked
        // TODO add your handling code here:
         // Obtener los valores de los campos de búsqueda
    String nombreCliente = campoTextoNombreCompleto.getText().trim();
    String telefonoCliente = campoTextoTelefono.getText().trim();
    LocalDateTime fechaReserva = dateTimePicker.getDateTimePermissive();
    
    // Construir la consulta basada en los filtros ingresados
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ConexionJPA");
    EntityManager em = emf.createEntityManager();
    
    StringBuilder queryStr = new StringBuilder("SELECT r FROM ReservaEntidad r WHERE 1=1");

if (!nombreCliente.isEmpty()) {
    queryStr.append(" AND r.cliente.nombreCompleto LIKE :nombreCliente");
}

if (!telefonoCliente.isEmpty()) {
    queryStr.append(" AND r.cliente.telefono LIKE :telefonoCliente");
}

if (fechaReserva != null) {
    queryStr.append(" AND r.fechaHoraReserva = :fechaReserva");
}

TypedQuery<ReservaEntidad> query = em.createQuery(queryStr.toString(), ReservaEntidad.class);
    
    // Establecer los parámetros de la consulta
    if (!nombreCliente.isEmpty()) {
        query.setParameter("nombreCliente", "%" + nombreCliente + "%");
    }
    if (!telefonoCliente.isEmpty()) {
        query.setParameter("telefonoCliente", "%" + telefonoCliente + "%");
    }
    if (fechaReserva != null) {
        query.setParameter("fechaReserva", Timestamp.valueOf(fechaReserva));
    }
    
    // Ejecutar la consulta y obtener los resultados
    List<ReservaEntidad> reservas = query.getResultList();
    
    // Si no se encuentran reservas, mostrar un mensaje
    if (reservas.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se encontraron reservas con los criterios de búsqueda.", "Resultado", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // Si se encuentran reservas, mostrarlas (puedes usar una tabla o lista para mostrar los resultados)
        mostrarReservas(reservas);
    }
        
    }//GEN-LAST:event_btnMostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsultaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMostrar;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JTextField campoTextoNombreCompleto;
    private javax.swing.JTextField campoTextoTelefono;
    private javax.swing.JPanel fldFechaReserva;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
