/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Util.ButtonRenderer;
import dto.ClienteDTO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import logica.ReservaNegocio;
import utilerias.ButtonEditor;

/**
 *
 * @author limon
 */
public class FrmSeleccionarCliente extends javax.swing.JFrame {

     List<ClienteDTO> clientes = new ArrayList<>();
    FrmConsultaCliente frmConsultaCliente;
    DefaultTableModel modelTable = new DefaultTableModel();
    FrmSeleccionarCliente frmSeleccionarCliente;
    ReservaNegocio reservaNegocio = new ReservaNegocio();
    /**
     * Creates new form FrmSeleccionarCliente
     */
    public FrmSeleccionarCliente(FrmConsultaCliente frmConsultaCliente, List<ClienteDTO> clientes) {
        this.clientes = clientes;
        this.frmConsultaCliente = frmConsultaCliente;
        initComponents();
        mostrarDatosTabla();
        
        configurarTablaMesas();
        mostrarDatosTabla();
    }

    public FrmSeleccionarCliente() {
    }
    
    private void configurarTablaMesas() {
        
        modelTable = (DefaultTableModel) tblCliente.getModel();
        TableColumnModel modeloColumnas = tblCliente.getColumnModel();

        // Configurar renderizador y editor de botón
        modelTable.setRowCount(0);
        modeloColumnas.getColumn(2).setCellRenderer(new ButtonRenderer("Generar", new Color(221,188,0)));
        modeloColumnas.getColumn(2).setCellEditor(new ButtonEditor("Generar", new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                 
                    if(tblCliente.getSelectedRow() == -1)
                        return;
                    
                    try {
                        
                        FrmReporte frm = new FrmReporte(frmSeleccionarCliente, reservaNegocio.buscarReservasPorCliente(clientes.get(tblCliente.getSelectedRow())), clientes.get(tblCliente.getSelectedRow()));
                        frm.setVisible(true);
                        dispose();
                        
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(frmSeleccionarCliente, "Error en al buscar reportes.", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                }
            }));

        
    } 
    
    private void mostrarDatosTabla() {
        DefaultTableModel model = (DefaultTableModel) tblCliente.getModel();
        
        for (ClienteDTO cliente : clientes) {
            Object[] row = new Object[2];
            row[0] = cliente.getNombreCompleto();
            row[1] = cliente.getTelefono();
            
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "nombreCompleto", "telefono", "Reporte"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrmMesas.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSeleccionarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables
}
